export const permissionsData = [
  {
    id: 'get_permissions',
    name: 'Get Permissions',
    description: 'Ability to retrieve permission information',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_organization',
    name: 'Delete Organization',
    description: 'Ability to delete an organization',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_account',
    name: 'Delete Account',
    description: 'Ability to delete user accounts',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'add_permission',
    name: 'Add Permission',
    description: 'Ability to add permissions to users',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'remove_permission',
    name: 'Remove Permission',
    description: 'Ability to remove permissions from users',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_organization',
    name: 'Create Organization',
    description: 'Ability to create new organizations',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_organization',
    name: 'View Organization',
    description: 'Ability to view organization details',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_organization',
    name: 'Edit Organization',
    description: 'Ability to edit organization details',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'link_organizations',
    name: 'Link Organizations',
    description: 'Ability to link organizations together',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_parent_company',
    name: 'Manage Parent Company',
    description: 'Ability to manage parent company settings',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'invite_staff',
    name: 'Invite Staff',
    description: 'Ability to invite new staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_staff_invitations',
    name: 'View Staff Invitations',
    description: 'Ability to view staff invitation history',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_staff_invitations',
    name: 'Manage Staff Invitations',
    description: 'Ability to manage staff invitations',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'add_staff',
    name: 'Add Staff',
    description: 'Ability to add staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'remove_staff',
    name: 'Remove Staff',
    description: 'Ability to remove staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_staff',
    name: 'View Staff',
    description: 'Ability to view staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_staff_role',
    name: 'Edit Staff Role',
    description: 'Ability to change staff roles',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_subjects',
    name: 'View Subjects',
    description: 'Ability to view subject information',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Patients',
      care_home: 'View Residents',
      education: 'View Students',
      service_provider: 'View Clients',
    },
  },
  {
    id: 'edit_subjects',
    name: 'Edit Subjects',
    description: 'Ability to edit subject information',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Edit Patients',
      care_home: 'Edit Residents',
      education: 'Edit Students',
      service_provider: 'Edit Clients',
    },
  },
  {
    id: 'view_subject_profile',
    name: 'View Subject Profile',
    description: 'Ability to view detailed subject profiles',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Patient Profile',
      care_home: 'View Resident Profile',
      education: 'View Student Profile',
      service_provider: 'View Client Profile',
    },
  },
  {
    id: 'view_subject_records',
    name: 'View Subject Records',
    description: 'Ability to view subject records',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Patient Records',
      care_home: 'View Resident Charts',
      education: 'View Student Records',
      service_provider: 'View Client Records',
    },
  },
  {
    id: 'create_subject_data',
    name: 'Create Subject Data',
    description: 'Ability to create subject data',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Create Patient Data',
      care_home: 'Create Resident Data',
      education: 'Create Student Data',
      service_provider: 'Create Client Data',
    },
  },
  {
    id: 'update_subject_data',
    name: 'Update Subject Data',
    description: 'Ability to update subject data',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Update Patient Data',
      care_home: 'Update Resident Data',
      education: 'Update Student Data',
      service_provider: 'Update Client Data',
    },
  },
  {
    id: 'delete_subject_data',
    name: 'Delete Subject Data',
    description: 'Ability to delete subject data',
    category: 'subject',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Delete Patient Data',
      care_home: 'Delete Resident Data',
      education: 'Delete Student Data',
      service_provider: 'Delete Client Data',
    },
  },
  {
    id: 'create_timesheets',
    name: 'Create Timesheets',
    description: 'Ability to create timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'approve_timesheets',
    name: 'Approve Timesheets',
    description: 'Ability to approve timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'reject_timesheets',
    name: 'Reject Timesheets',
    description: 'Ability to reject timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_timesheets',
    name: 'Delete Timesheets',
    description: 'Ability to delete timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_timesheets',
    name: 'View Timesheets',
    description: 'Ability to view timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'scan_timesheets',
    name: 'Scan Timesheets',
    description: 'Ability to scan and process timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_timesheets',
    name: 'Edit Timesheets',
    description: 'Ability to edit timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_locations',
    name: 'View Locations',
    description: 'Ability to view organization locations',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Hospitals',
      care_home: 'View Homes',
      education: 'View Schools',
      retail: 'View Stores',
    },
  },
  {
    id: 'edit_locations',
    name: 'Edit Locations',
    description: 'Ability to edit location information',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Edit Hospitals',
      care_home: 'Edit Homes',
      education: 'Edit Schools',
      retail: 'Edit Stores',
    },
  },
  {
    id: 'view_providers',
    name: 'View Providers',
    description: 'Ability to view service providers',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Medical Providers',
      care_home: 'View Care Agencies',
      education: 'View Educational Providers',
      retail: 'View Suppliers',
    },
  },
  {
    id: 'edit_providers',
    name: 'Edit Providers',
    description: 'Ability to edit provider information',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Edit Medical Providers',
      care_home: 'Edit Care Agencies',
      education: 'Edit Educational Providers',
      retail: 'Edit Suppliers',
    },
  },
  {
    id: 'view_chat',
    name: 'View Chat',
    description: 'Ability to view chat messages',
    category: 'communication',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_chat',
    name: 'Edit Chat',
    description: 'Ability to edit and manage chat messages',
    category: 'communication',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_invoices',
    name: 'View Invoices',
    description: 'Ability to view invoices',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_invoices',
    name: 'Edit Invoices',
    description: 'Ability to create and edit invoices',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_payments',
    name: 'View Payments',
    description: 'Ability to view payment records',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_payments',
    name: 'Edit Payments',
    description: 'Ability to manage payment records',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_payroll',
    name: 'View Payroll',
    description: 'Ability to view payroll information',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'process_payroll',
    name: 'Process Payroll',
    description: 'Ability to process payroll',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_financial_reports',
    name: 'View Financial Reports',
    description: 'Ability to view financial reports',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_financial_reports',
    name: 'Create Financial Reports',
    description: 'Ability to create financial reports',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_settings',
    name: 'View Settings',
    description: 'Ability to view organization settings',
    category: 'settings',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_settings',
    name: 'Edit Settings',
    description: 'Ability to edit organization settings',
    category: 'settings',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_dashboard',
    name: 'View Dashboard',
    description: 'Ability to view organization dashboard',
    category: 'dashboard',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_schedules',
    name: 'View Schedules',
    description: 'Ability to view staff schedules',
    category: 'schedule',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_schedules',
    name: 'Edit Schedules',
    description: 'Ability to edit staff schedules',
    category: 'schedule',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_shift_pattern',
    name: 'Create Shift Pattern',
    description: 'Ability to create shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_shift_pattern',
    name: 'Edit Shift Pattern',
    description: 'Ability to edit shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_shift_pattern',
    name: 'Delete Shift Pattern',
    description: 'Ability to delete shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_shift_pattern',
    name: 'View Shift Pattern',
    description: 'Ability to view shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_shift',
    name: 'Create Shift',
    description: 'Ability to create new shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_shift',
    name: 'Delete Shift',
    description: 'Ability to delete shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'update_shift',
    name: 'Update Shift',
    description: 'Ability to update shift details',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'assign_users',
    name: 'Assign Users',
    description: 'Ability to assign users to shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'unassign_users',
    name: 'Unassign Users',
    description: 'Ability to unassign users from shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_shift',
    name: 'View Shift',
    description: 'Ability to view shift details',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_service_plans',
    name: 'View Service Plans',
    description: 'Ability to view service plans',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Treatment Plans',
      care_home: 'View Care Plans',
      education: 'View Learning Plans',
    },
  },
  {
    id: 'create_service_plans',
    name: 'Create Service Plans',
    description: 'Ability to create service plans',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Create Treatment Plans',
      care_home: 'Create Care Plans',
      education: 'Create Learning Plans',
    },
  },
  {
    id: 'update_service_plans',
    name: 'Update Service Plans',
    description: 'Ability to update service plans',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Update Treatment Plans',
      care_home: 'Update Care Plans',
      education: 'Update Learning Plans',
    },
  },
  {
    id: 'delete_service_plans',
    name: 'Delete Service Plans',
    description: 'Ability to delete service plans',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Delete Treatment Plans',
      care_home: 'Delete Care Plans',
      education: 'Delete Learning Plans',
    },
  },
  {
    id: 'view_service_notes',
    name: 'View Service Notes',
    description: 'Ability to view service notes',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Medical Notes',
      care_home: 'View Care Notes',
      education: 'View Progress Notes',
    },
  },
  {
    id: 'create_service_notes',
    name: 'Create Service Notes',
    description: 'Ability to create service notes',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Create Medical Notes',
      care_home: 'Create Care Notes',
      education: 'Create Progress Notes',
    },
  },
  {
    id: 'update_service_notes',
    name: 'Update Service Notes',
    description: 'Ability to update service notes',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Update Medical Notes',
      care_home: 'Update Care Notes',
      education: 'Update Progress Notes',
    },
  },
  {
    id: 'delete_service_notes',
    name: 'Delete Service Notes',
    description: 'Ability to delete service notes',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Delete Medical Notes',
      care_home: 'Delete Care Notes',
      education: 'Delete Progress Notes',
    },
  },
  {
    id: 'create_routines',
    name: 'Create Routines',
    description: 'Ability to create service routines',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Create Treatment Routines',
      care_home: 'Create Care Routines',
      education: 'Create Learning Activities',
    },
  },
  {
    id: 'update_routines',
    name: 'Update Routines',
    description: 'Ability to update service routines',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Update Treatment Routines',
      care_home: 'Update Care Routines',
      education: 'Update Learning Activities',
    },
  },
  {
    id: 'delete_routines',
    name: 'Delete Routines',
    description: 'Ability to delete service routines',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Delete Treatment Routines',
      care_home: 'Delete Care Routines',
      education: 'Delete Learning Activities',
    },
  },
  {
    id: 'view_routines',
    name: 'View Routines',
    description: 'Ability to view service routines',
    category: 'service',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Treatment Routines',
      care_home: 'View Care Routines',
      education: 'View Learning Activities',
    },
  },
  {
    id: 'view_health_records',
    name: 'View Health Records',
    description: 'Ability to view health records',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'View Medical Records',
      care_home: 'View Health Records',
    },
  },
  {
    id: 'create_health_records',
    name: 'Create Health Records',
    description: 'Ability to create health records',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Create Medical Records',
      care_home: 'Create Health Records',
    },
  },
  {
    id: 'update_health_records',
    name: 'Update Health Records',
    description: 'Ability to update health records',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Update Medical Records',
      care_home: 'Update Health Records',
    },
  },
  {
    id: 'delete_health_records',
    name: 'Delete Health Records',
    description: 'Ability to delete health records',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Delete Medical Records',
      care_home: 'Delete Health Records',
    },
  },
  {
    id: 'view_medications',
    name: 'View Medications',
    description: 'Ability to view medications',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'View Patient Medications',
      care_home: 'View Resident Medications',
    },
  },
  {
    id: 'create_medications',
    name: 'Create Medications',
    description: 'Ability to add medications',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Add Patient Medications',
      care_home: 'Add Resident Medications',
    },
  },
  {
    id: 'update_medications',
    name: 'Update Medications',
    description: 'Ability to update medications',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Update Patient Medications',
      care_home: 'Update Resident Medications',
    },
  },
  {
    id: 'delete_medications',
    name: 'Delete Medications',
    description: 'Ability to delete medications',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'Delete Patient Medications',
      care_home: 'Delete Resident Medications',
    },
  },
  {
    id: 'view_health_conditions',
    name: 'View Health Conditions',
    description: 'Ability to view health conditions',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {
      hospital: 'View Medical Conditions',
      care_home: 'View Health Conditions',
    },
  },
  {
    id: 'view_allergies',
    name: 'View Allergies',
    description: 'Ability to view allergies',
    category: 'health',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {},
  },
  {
    id: 'create_tasks',
    name: 'Create Tasks',
    description: 'Ability to create tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },

  {
    id: 'update_tasks',
    name: 'Update Tasks',
    description: 'Ability to update tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_tasks',
    name: 'Delete Tasks',
    description: 'Ability to delete tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_tasks',
    name: 'View Tasks',
    description: 'Ability to view tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_historical_tasks',
    name: 'View Historical Tasks',
    description: 'Ability to view completed tasks history',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_tasks_by_date_range',
    name: 'View Tasks By Date Range',
    description: 'Ability to view tasks within a date range',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_completion_rate',
    name: 'View Completion Rate',
    description: 'Ability to view task completion rates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'reschedule_tasks',
    name: 'Reschedule Tasks',
    description: 'Ability to reschedule tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'generate_tasks',
    name: 'Generate Tasks',
    description: 'Ability to generate tasks from templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'mark_overdue_tasks',
    name: 'Mark Overdue Tasks',
    description: 'Ability to mark tasks as overdue',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'complete_tasks',
    name: 'Complete Tasks',
    description: 'Ability to mark tasks as complete',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_upcoming_tasks',
    name: 'View Upcoming Tasks',
    description: 'Ability to view upcoming tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_pending_tasks',
    name: 'View Pending Tasks',
    description: 'Ability to view pending tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_all_tasks',
    name: 'View All Tasks',
    description: 'Ability to view all tasks in the system',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_task_details',
    name: 'View Task Details',
    description: 'Ability to view detailed task information',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_subject_tasks',
    name: 'View Subject Tasks',
    description: 'Ability to view tasks for specific subjects',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'View Patient Tasks',
      care_home: 'View Resident Tasks',
      education: 'View Student Tasks',
      service_provider: 'View Client Tasks',
    },
  },
  {
    id: 'resolve_task',
    name: 'Resolve Task',
    description: 'Ability to resolve tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'add_task',
    name: 'Add Task',
    description: 'Ability to add new tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_active_tasks',
    name: 'View Active Tasks',
    description: 'Ability to view currently active tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_overdue_tasks',
    name: 'View Overdue Tasks',
    description: 'Ability to view overdue tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_cancelled_tasks',
    name: 'View Cancelled Tasks',
    description: 'Ability to view cancelled tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'assign_task',
    name: 'Assign Task',
    description: 'Ability to assign tasks to staff',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'transfer_task',
    name: 'Transfer Task',
    description: 'Ability to transfer tasks between staff',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'bulk_update_tasks',
    name: 'Bulk Update Tasks',
    description: 'Ability to update multiple tasks at once',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_task_templates',
    name: 'View Task Templates',
    description: 'Ability to view task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_task_templates',
    name: 'Create Task Templates',
    description: 'Ability to create task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_task_templates',
    name: 'Edit Task Templates',
    description: 'Ability to edit task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_task_templates',
    name: 'Delete Task Templates',
    description: 'Ability to delete task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_organization_invitations',
    name: 'View Organization Invitations',
    description: 'Ability to view invitations between organizations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'accept_invitation',
    name: 'Accept Invitation',
    description: 'Ability to accept invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'reject_invitation',
    name: 'Reject Invitation',
    description: 'Ability to reject invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_invitations',
    name: 'View Invitations',
    description: 'Ability to view all invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_invitations',
    name: 'Edit Invitations',
    description: 'Ability to edit invitation details',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_invitations',
    name: 'Delete Invitations',
    description: 'Ability to delete invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_invitations',
    name: 'Create Invitations',
    description: 'Ability to create invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'invite_organization',
    name: 'Invite Organization',
    description: 'Ability to invite other organizations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_notifications',
    name: 'View Notifications',
    description: 'Ability to view notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_notifications',
    name: 'Delete Notifications',
    description: 'Ability to delete notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_notifications',
    name: 'Create Notifications',
    description: 'Ability to create notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_notifications',
    name: 'Edit Notifications',
    description: 'Ability to edit notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_reports',
    name: 'View Reports',
    description: 'Ability to view reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_reports',
    name: 'Create Reports',
    description: 'Ability to create reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_reports',
    name: 'Edit Reports',
    description: 'Ability to edit reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_reports',
    name: 'Delete Reports',
    description: 'Ability to delete reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_employee_records',
    name: 'View Employee Records',
    description: 'Ability to view employee records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_employee_records',
    name: 'Edit Employee Records',
    description: 'Ability to edit employee records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_training_records',
    name: 'View Training Records',
    description: 'Ability to view staff training records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_training_records',
    name: 'Edit Training Records',
    description: 'Ability to edit staff training records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'schedule_training',
    name: 'Schedule Training',
    description: 'Ability to schedule staff training',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_audit_logs',
    name: 'View Audit Logs',
    description: 'Ability to view system audit logs',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'perform_audits',
    name: 'Perform Audits',
    description: 'Ability to perform system audits',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_quality_metrics',
    name: 'View Quality Metrics',
    description: 'Ability to view quality metrics',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_quality_metrics',
    name: 'Edit Quality Metrics',
    description: 'Ability to edit quality metrics',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_compliance_reports',
    name: 'View Compliance Reports',
    description: 'Ability to view compliance reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_compliance',
    name: 'Manage Compliance',
    description: 'Ability to manage compliance settings',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_incident_reports',
    name: 'View Incident Reports',
    description: 'Ability to view incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_incident_reports',
    name: 'Create Incident Reports',
    description: 'Ability to create incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_incident_reports',
    name: 'Manage Incident Reports',
    description: 'Ability to manage incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_inventory',
    name: 'View Inventory',
    description: 'Ability to view inventory',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_inventory',
    name: 'Manage Inventory',
    description: 'Ability to manage inventory',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_supplier_contracts',
    name: 'View Supplier Contracts',
    description: 'Ability to view supplier contracts',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_supplier_contracts',
    name: 'Manage Supplier Contracts',
    description: 'Ability to manage supplier contracts',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_group',
    name: 'Create Group',
    description: 'Ability to create staff or subject groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {
      hospital: 'Create Staff or Patient Groups',
      care_home: 'Create Staff or Resident Groups',
      education: 'Create Staff or Student Groups',
    },
  },
  {
    id: 'view_group',
    name: 'View Group',
    description: 'Ability to view groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'edit_group',
    name: 'Edit Group',
    description: 'Ability to edit group details',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'delete_group',
    name: 'Delete Group',
    description: 'Ability to delete groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'add_group_member',
    name: 'Add Group Member',
    description: 'Ability to add members to groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'update_group',
    name: 'Update Group',
    description: 'Ability to update group settings',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_leave_request',
    name: 'Create Leave Request',
    description: 'Ability to create leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_leave_requests',
    name: 'View Leave Requests',
    description: 'Ability to view leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_leave_balance',
    name: 'View Leave Balance',
    description: 'Ability to view leave balance',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_all_leave_balances',
    name: 'View All Leave Balances',
    description: 'Ability to view all staff leave balances',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_leave_requests',
    name: 'Manage Leave Requests',
    description: 'Ability to approve/reject leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_leave_policy',
    name: 'Manage Leave Policy',
    description: 'Ability to set leave policies',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_leave_policy',
    name: 'View Leave Policy',
    description: 'Ability to view leave policies',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_system',
    name: 'Manage System',
    description: 'Full system management capabilities',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'create_system_admin',
    name: 'Create System Admin',
    description: 'Ability to create system administrators',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_permissions',
    name: 'Manage Permissions',
    description: 'Ability to manage system permissions',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_roles',
    name: 'Manage Roles',
    description: 'Ability to manage system roles',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_all_organizations',
    name: 'View All Organizations',
    description: 'Ability to view all organizations in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_all_organizations',
    name: 'Manage All Organizations',
    description: 'Ability to manage all organizations in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'view_all_users',
    name: 'View All Users',
    description: 'Ability to view all users in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manage_all_users',
    name: 'Manage All Users',
    description: 'Ability to manage all users in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
    organizationCategories: ['*'],
    displayNames: {},
  },
];

export const rolesData = [
  {
    id: 'owner',
    name: 'Owner',
    description: 'Organization owner with full access',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 1,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'admin',
    name: 'Administrator',
    description: 'Organization administrator with broad access',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 2,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'manager',
    name: 'Manager',
    description: 'Department or team manager',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'doctor',
    name: 'Doctor',
    description: 'Medical doctor with clinical responsibilities',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['hospital', 'healthcare'],
    displayNames: {},
  },
  {
    id: 'nurse',
    name: 'Nurse',
    description: 'Registered nurse with clinical responsibilities',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['hospital', 'care_home', 'healthcare'],
    displayNames: {},
  },
  {
    id: 'care_assistant',
    name: 'Care Assistant',
    description: 'Care staff providing direct care',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 5,
    organizationCategories: ['care_home', 'healthcare', 'hospital'],
    displayNames: {
      hospital: 'Healthcare Assistant',
      care_home: 'Carer',
    },
  },
  {
    id: 'senior_care_assistant',
    name: 'Senior Care Assistant',
    description: 'Senior care staff with supervisory duties',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 4,
    organizationCategories: ['care_home', 'healthcare', 'hospital'],
    displayNames: {
      hospital: 'Senior Healthcare Assistant',
      care_home: 'Senior Carer',
    },
  },
  {
    id: 'teacher',
    name: 'Teacher',
    description: 'Educational instructor',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['education', 'school'],
    displayNames: {},
  },
  {
    id: 'admin_staff',
    name: 'Administrative Staff',
    description: 'General administrative personnel',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 4,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'hr_manager',
    name: 'HR Manager',
    description: 'Human resources manager',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'accountant',
    name: 'Accountant',
    description: 'Financial management staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'quality_assurance',
    name: 'Quality Assurance',
    description: 'Staff responsible for quality standards',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 3,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'procurement_officer',
    name: 'Procurement Officer',
    description: 'Staff responsible for purchasing and suppliers',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 4,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'staff',
    name: 'Staff',
    description: 'General staff member',
    contextType: 'ORGANIZATION',
    isSystem: true,
    hierarchyLevel: 6,
    organizationCategories: ['*'],
    displayNames: {},
  },
  {
    id: 'system_admin',
    name: 'System Administrator',
    description:
      'Top-level system administrator with access to all system functions',
    contextType: 'SYSTEM',
    isSystem: true,
    hierarchyLevel: 0,
    organizationCategories: ['*'],
    displayNames: {},
  },
];
