export const permissionsData = [
  // System Administration Permissions
  {
    id: 'get_permissions',
    name: 'Get Permissions',
    description: 'Ability to retrieve permission information',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_organization',
    name: 'Delete Organization',
    description: 'Ability to delete an organization',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_account',
    name: 'Delete Account',
    description: 'Ability to delete user accounts',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'add_permission',
    name: 'Add Permission',
    description: 'Ability to add permissions to users',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'remove_permission',
    name: 'Remove Permission',
    description: 'Ability to remove permissions from users',
    category: 'system',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Organization Management Permissions
  {
    id: 'create_organization',
    name: 'Create Organization',
    description: 'Ability to create new organizations',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_organization',
    name: 'View Organization',
    description: 'Ability to view organization details',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_organization',
    name: 'Edit Organization',
    description: 'Ability to edit organization details',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'link_organizations',
    name: 'Link Organizations',
    description: 'Ability to link organizations together',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_parent_company',
    name: 'Manage Parent Company',
    description: 'Ability to manage parent company settings',
    category: 'organization',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Staff Management Permissions
  {
    id: 'invite_staff',
    name: 'Invite Staff',
    description: 'Ability to invite new staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_staff_invitations',
    name: 'View Staff Invitations',
    description: 'Ability to view staff invitation history',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_staff_invitations',
    name: 'Manage Staff Invitations',
    description: 'Ability to manage staff invitations',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'add_staff',
    name: 'Add Staff',
    description: 'Ability to add staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'remove_staff',
    name: 'Remove Staff',
    description: 'Ability to remove staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_staff',
    name: 'View Staff',
    description: 'Ability to view staff members',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_staff_role',
    name: 'Edit Staff Role',
    description: 'Ability to change staff roles',
    category: 'staff',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Client/Resident Management Permissions
  {
    id: 'view_clients',
    name: 'View Clients',
    description: 'Ability to view client information',
    category: 'client',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_clients',
    name: 'Edit Clients',
    description: 'Ability to edit client information',
    category: 'client',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_residents',
    name: 'View Residents',
    description: 'Ability to view resident information',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_resident_profile',
    name: 'View Resident Profile',
    description: 'Ability to view detailed resident profiles',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_resident_charts',
    name: 'View Resident Charts',
    description: 'Ability to view resident charts and metrics',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Timesheet Permissions
  {
    id: 'create_timesheets',
    name: 'Create Timesheets',
    description: 'Ability to create timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'approve_timesheets',
    name: 'Approve Timesheets',
    description: 'Ability to approve timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'reject_timesheets',
    name: 'Reject Timesheets',
    description: 'Ability to reject timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_timesheets',
    name: 'Delete Timesheets',
    description: 'Ability to delete timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_timesheets',
    name: 'View Timesheets',
    description: 'Ability to view timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'scan_timesheets',
    name: 'Scan Timesheets',
    description: 'Ability to scan and process timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_timesheets',
    name: 'Edit Timesheets',
    description: 'Ability to edit timesheets',
    category: 'timesheet',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Organization View Permissions
  {
    id: 'view_homes',
    name: 'View Homes',
    description: 'Ability to view care homes',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_homes',
    name: 'Edit Homes',
    description: 'Ability to edit care home information',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_agencies',
    name: 'View Agencies',
    description: 'Ability to view care agencies',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_agencies',
    name: 'Edit Agencies',
    description: 'Ability to edit care agency information',
    category: 'organization_view',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Communication Permissions
  {
    id: 'view_chat',
    name: 'View Chat',
    description: 'Ability to view chat messages',
    category: 'communication',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_chat',
    name: 'Edit Chat',
    description: 'Ability to edit and manage chat messages',
    category: 'communication',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Finance Permissions
  {
    id: 'view_invoices',
    name: 'View Invoices',
    description: 'Ability to view invoices',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_invoices',
    name: 'Edit Invoices',
    description: 'Ability to create and edit invoices',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_payments',
    name: 'View Payments',
    description: 'Ability to view payment records',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_payments',
    name: 'Edit Payments',
    description: 'Ability to manage payment records',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_payroll',
    name: 'View Payroll',
    description: 'Ability to view payroll information',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'process_payroll',
    name: 'Process Payroll',
    description: 'Ability to process payroll',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_financial_reports',
    name: 'View Financial Reports',
    description: 'Ability to view financial reports',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_financial_reports',
    name: 'Create Financial Reports',
    description: 'Ability to create financial reports',
    category: 'finance',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Settings & Dashboard Permissions
  {
    id: 'view_settings',
    name: 'View Settings',
    description: 'Ability to view organization settings',
    category: 'settings',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_settings',
    name: 'Edit Settings',
    description: 'Ability to edit organization settings',
    category: 'settings',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_dashboard',
    name: 'View Dashboard',
    description: 'Ability to view organization dashboard',
    category: 'dashboard',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Schedule Permissions
  {
    id: 'view_schedules',
    name: 'View Schedules',
    description: 'Ability to view staff schedules',
    category: 'schedule',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_schedules',
    name: 'Edit Schedules',
    description: 'Ability to edit staff schedules',
    category: 'schedule',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Shift Pattern Permissions
  {
    id: 'create_shift_pattern',
    name: 'Create Shift Pattern',
    description: 'Ability to create shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_shift_pattern',
    name: 'Edit Shift Pattern',
    description: 'Ability to edit shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_shift_pattern',
    name: 'Delete Shift Pattern',
    description: 'Ability to delete shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_shift_pattern',
    name: 'View Shift Pattern',
    description: 'Ability to view shift patterns',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Shift Management Permissions
  {
    id: 'create_shift',
    name: 'Create Shift',
    description: 'Ability to create new shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_shift',
    name: 'Delete Shift',
    description: 'Ability to delete shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_shift',
    name: 'Update Shift',
    description: 'Ability to update shift details',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'assign_users',
    name: 'Assign Users',
    description: 'Ability to assign users to shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'unassign_users',
    name: 'Unassign Users',
    description: 'Ability to unassign users from shifts',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_shift',
    name: 'View Shift',
    description: 'Ability to view shift details',
    category: 'shift',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Resident Data Permissions
  {
    id: 'create_resident_data',
    name: 'Create Resident Data',
    description: 'Ability to create resident data',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_resident_data',
    name: 'Update Resident Data',
    description: 'Ability to update resident data',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_resident_data',
    name: 'Delete Resident Data',
    description: 'Ability to delete resident data',
    category: 'resident',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Care Routines Permissions
  {
    id: 'create_routines',
    name: 'Create Routines',
    description: 'Ability to create care routines',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_routines',
    name: 'Update Routines',
    description: 'Ability to update care routines',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_routines',
    name: 'Delete Routines',
    description: 'Ability to delete care routines',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_routines',
    name: 'View Routines',
    description: 'Ability to view care routines',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Task Management Permissions
  {
    id: 'create_tasks',
    name: 'Create Tasks',
    description: 'Ability to create tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_tasks',
    name: 'Update Tasks',
    description: 'Ability to update tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_tasks',
    name: 'Delete Tasks',
    description: 'Ability to delete tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_tasks',
    name: 'View Tasks',
    description: 'Ability to view tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_historical_tasks',
    name: 'View Historical Tasks',
    description: 'Ability to view completed tasks history',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_tasks_by_date_range',
    name: 'View Tasks By Date Range',
    description: 'Ability to view tasks within a date range',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_completion_rate',
    name: 'View Completion Rate',
    description: 'Ability to view task completion rates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'reschedule_tasks',
    name: 'Reschedule Tasks',
    description: 'Ability to reschedule tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'generate_tasks',
    name: 'Generate Tasks',
    description: 'Ability to generate tasks from templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'mark_overdue_tasks',
    name: 'Mark Overdue Tasks',
    description: 'Ability to mark tasks as overdue',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'complete_tasks',
    name: 'Complete Tasks',
    description: 'Ability to mark tasks as complete',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_upcoming_tasks',
    name: 'View Upcoming Tasks',
    description: 'Ability to view upcoming tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_pending_tasks',
    name: 'View Pending Tasks',
    description: 'Ability to view pending tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_all_tasks',
    name: 'View All Tasks',
    description: 'Ability to view all tasks in the system',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_task_details',
    name: 'View Task Details',
    description: 'Ability to view detailed task information',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_resident_tasks',
    name: 'View Resident Tasks',
    description: 'Ability to view tasks for specific residents',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'resolve_task',
    name: 'Resolve Task',
    description: 'Ability to resolve tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'add_task',
    name: 'Add Task',
    description: 'Ability to add new tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_active_tasks',
    name: 'View Active Tasks',
    description: 'Ability to view currently active tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_overdue_tasks',
    name: 'View Overdue Tasks',
    description: 'Ability to view overdue tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_cancelled_tasks',
    name: 'View Cancelled Tasks',
    description: 'Ability to view cancelled tasks',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'assign_task',
    name: 'Assign Task',
    description: 'Ability to assign tasks to staff',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'transfer_task',
    name: 'Transfer Task',
    description: 'Ability to transfer tasks between staff',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'bulk_update_tasks',
    name: 'Bulk Update Tasks',
    description: 'Ability to update multiple tasks at once',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_task_templates',
    name: 'View Task Templates',
    description: 'Ability to view task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_task_templates',
    name: 'Create Task Templates',
    description: 'Ability to create task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_task_templates',
    name: 'Edit Task Templates',
    description: 'Ability to edit task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_task_templates',
    name: 'Delete Task Templates',
    description: 'Ability to delete task templates',
    category: 'task',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Care Plans and Notes Permissions
  {
    id: 'view_care_plans',
    name: 'View Care Plans',
    description: 'Ability to view resident care plans',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_care_plans',
    name: 'Create Care Plans',
    description: 'Ability to create resident care plans',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_care_plans',
    name: 'Update Care Plans',
    description: 'Ability to update resident care plans',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_care_plans',
    name: 'Delete Care Plans',
    description: 'Ability to delete resident care plans',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_care_notes',
    name: 'View Care Notes',
    description: 'Ability to view resident care notes',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_care_notes',
    name: 'Create Care Notes',
    description: 'Ability to create resident care notes',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_care_notes',
    name: 'Update Care Notes',
    description: 'Ability to update resident care notes',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_care_notes',
    name: 'Delete Care Notes',
    description: 'Ability to delete resident care notes',
    category: 'care',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Medical Information Permissions
  {
    id: 'view_medications',
    name: 'View Medications',
    description: 'Ability to view resident medications',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_medications',
    name: 'Create Medications',
    description: 'Ability to add resident medications',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_medications',
    name: 'Update Medications',
    description: 'Ability to update resident medications',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_medications',
    name: 'Delete Medications',
    description: 'Ability to delete resident medications',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_medical_records',
    name: 'View Medical Records',
    description: 'Ability to view resident medical records',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_medical_records',
    name: 'Create Medical Records',
    description: 'Ability to create resident medical records',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_medical_records',
    name: 'Update Medical Records',
    description: 'Ability to update resident medical records',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_medical_records',
    name: 'Delete Medical Records',
    description: 'Ability to delete resident medical records',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_medical_conditions',
    name: 'View Medical Conditions',
    description: 'Ability to view resident medical conditions',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_medical_conditions',
    name: 'Create Medical Conditions',
    description: 'Ability to add resident medical conditions',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_medical_conditions',
    name: 'Update Medical Conditions',
    description: 'Ability to update resident medical conditions',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_medical_conditions',
    name: 'Delete Medical Conditions',
    description: 'Ability to delete resident medical conditions',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_allergies',
    name: 'View Allergies',
    description: 'Ability to view resident allergies',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_allergies',
    name: 'Create Allergies',
    description: 'Ability to add resident allergies',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_allergies',
    name: 'Update Allergies',
    description: 'Ability to update resident allergies',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_allergies',
    name: 'Delete Allergies',
    description: 'Ability to delete resident allergies',
    category: 'medical',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Invitation Management Permissions
  {
    id: 'view_organization_invitations',
    name: 'View Organization Invitations',
    description: 'Ability to view invitations between organizations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'accept_invitation',
    name: 'Accept Invitation',
    description: 'Ability to accept invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'reject_invitation',
    name: 'Reject Invitation',
    description: 'Ability to reject invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_invitations',
    name: 'View Invitations',
    description: 'Ability to view all invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_invitations',
    name: 'Edit Invitations',
    description: 'Ability to edit invitation details',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_invitations',
    name: 'Delete Invitations',
    description: 'Ability to delete invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_invitations',
    name: 'Create Invitations',
    description: 'Ability to create invitations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'invite_organization',
    name: 'Invite Organization',
    description: 'Ability to invite other organizations',
    category: 'invitation',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Notification Management Permissions
  {
    id: 'view_notifications',
    name: 'View Notifications',
    description: 'Ability to view notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_notifications',
    name: 'Delete Notifications',
    description: 'Ability to delete notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_notifications',
    name: 'Create Notifications',
    description: 'Ability to create notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_notifications',
    name: 'Edit Notifications',
    description: 'Ability to edit notifications',
    category: 'notification',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Report Management Permissions
  {
    id: 'view_reports',
    name: 'View Reports',
    description: 'Ability to view reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_reports',
    name: 'Create Reports',
    description: 'Ability to create reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_reports',
    name: 'Edit Reports',
    description: 'Ability to edit reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_reports',
    name: 'Delete Reports',
    description: 'Ability to delete reports',
    category: 'report',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // HR Management Permissions
  {
    id: 'view_employee_records',
    name: 'View Employee Records',
    description: 'Ability to view employee records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_employee_records',
    name: 'Edit Employee Records',
    description: 'Ability to edit employee records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_training_records',
    name: 'View Training Records',
    description: 'Ability to view staff training records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_training_records',
    name: 'Edit Training Records',
    description: 'Ability to edit staff training records',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'schedule_training',
    name: 'Schedule Training',
    description: 'Ability to schedule staff training',
    category: 'hr',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Quality and Compliance Permissions
  {
    id: 'view_audit_logs',
    name: 'View Audit Logs',
    description: 'Ability to view system audit logs',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'perform_audits',
    name: 'Perform Audits',
    description: 'Ability to perform system audits',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_quality_metrics',
    name: 'View Quality Metrics',
    description: 'Ability to view quality metrics',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_quality_metrics',
    name: 'Edit Quality Metrics',
    description: 'Ability to edit quality metrics',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_compliance_reports',
    name: 'View Compliance Reports',
    description: 'Ability to view compliance reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_compliance',
    name: 'Manage Compliance',
    description: 'Ability to manage compliance settings',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_incident_reports',
    name: 'View Incident Reports',
    description: 'Ability to view incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'create_incident_reports',
    name: 'Create Incident Reports',
    description: 'Ability to create incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_incident_reports',
    name: 'Manage Incident Reports',
    description: 'Ability to manage incident reports',
    category: 'quality',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Inventory Management Permissions
  {
    id: 'view_inventory',
    name: 'View Inventory',
    description: 'Ability to view inventory',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_inventory',
    name: 'Manage Inventory',
    description: 'Ability to manage inventory',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_supplier_contracts',
    name: 'View Supplier Contracts',
    description: 'Ability to view supplier contracts',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_supplier_contracts',
    name: 'Manage Supplier Contracts',
    description: 'Ability to manage supplier contracts',
    category: 'inventory',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Group Management Permissions
  {
    id: 'create_group',
    name: 'Create Group',
    description: 'Ability to create staff or resident groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_group',
    name: 'View Group',
    description: 'Ability to view groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'edit_group',
    name: 'Edit Group',
    description: 'Ability to edit group details',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'delete_group',
    name: 'Delete Group',
    description: 'Ability to delete groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'add_group_member',
    name: 'Add Group Member',
    description: 'Ability to add members to groups',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'update_group',
    name: 'Update Group',
    description: 'Ability to update group settings',
    category: 'group',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  // Leave Management Permissions
  {
    id: 'create_leave_request',
    name: 'Create Leave Request',
    description: 'Ability to create leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_leave_requests',
    name: 'View Leave Requests',
    description: 'Ability to view leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_leave_balance',
    name: 'View Leave Balance',
    description: 'Ability to view leave balance',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_all_leave_balances',
    name: 'View All Leave Balances',
    description: 'Ability to view all staff leave balances',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_leave_requests',
    name: 'Manage Leave Requests',
    description: 'Ability to approve/reject leave requests',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'manage_leave_policy',
    name: 'Manage Leave Policy',
    description: 'Ability to set leave policies',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },
  {
    id: 'view_leave_policy',
    name: 'View Leave Policy',
    description: 'Ability to view leave policies',
    category: 'leave',
    contextType: 'ORGANIZATION',
    isSystem: true,
  },

  //system

  {
    id: 'manage_system',
    name: 'Manage System',
    description: 'Full system management capabilities',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'create_system_admin',
    name: 'Create System Admin',
    description: 'Ability to create system administrators',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'manage_permissions',
    name: 'Manage Permissions',
    description: 'Ability to manage system permissions',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'manage_roles',
    name: 'Manage Roles',
    description: 'Ability to manage system roles',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'view_all_organizations',
    name: 'View All Organizations',
    description: 'Ability to view all organizations in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'manage_all_organizations',
    name: 'Manage All Organizations',
    description: 'Ability to manage all organizations in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'view_all_users',
    name: 'View All Users',
    description: 'Ability to view all users in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
  {
    id: 'manage_all_users',
    name: 'Manage All Users',
    description: 'Ability to manage all users in the system',
    category: 'system',
    contextType: 'SYSTEM',
    isSystem: true,
  },
];

export const permissionImplicationsData = [
  // Admin permissions imply more specific permissions
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'manage_permissions',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'manage_roles',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'view_all_organizations',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'manage_all_organizations',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'view_all_users',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'manage_all_users',
  },
  {
    parentPermissionId: 'manage_system',
    childPermissionId: 'create_system_admin',
  },
  {
    parentPermissionId: 'manage_all_organizations',
    childPermissionId: 'view_all_organizations',
  },
  {
    parentPermissionId: 'manage_all_organizations',
    childPermissionId: 'create_organization',
  },
  {
    parentPermissionId: 'manage_all_organizations',
    childPermissionId: 'delete_organization',
  },
  {
    parentPermissionId: 'manage_all_users',
    childPermissionId: 'view_all_users',
  },
  {
    parentPermissionId: 'manage_permissions',
    childPermissionId: 'add_permission',
  },
  {
    parentPermissionId: 'manage_permissions',
    childPermissionId: 'remove_permission',
  },
  {
    parentPermissionId: 'manage_permissions',
    childPermissionId: 'get_permissions',
  },
  {
    parentPermissionId: 'edit_organization',
    childPermissionId: 'view_organization',
  },
  { parentPermissionId: 'edit_staff_role', childPermissionId: 'view_staff' },
  { parentPermissionId: 'edit_clients', childPermissionId: 'view_clients' },
  {
    parentPermissionId: 'edit_timesheets',
    childPermissionId: 'view_timesheets',
  },
  {
    parentPermissionId: 'approve_timesheets',
    childPermissionId: 'view_timesheets',
  },
  {
    parentPermissionId: 'reject_timesheets',
    childPermissionId: 'view_timesheets',
  },
  { parentPermissionId: 'edit_homes', childPermissionId: 'view_homes' },
  { parentPermissionId: 'edit_agencies', childPermissionId: 'view_agencies' },
  { parentPermissionId: 'edit_invoices', childPermissionId: 'view_invoices' },
  { parentPermissionId: 'edit_payments', childPermissionId: 'view_payments' },
  { parentPermissionId: 'edit_settings', childPermissionId: 'view_settings' },
  {
    parentPermissionId: 'edit_schedules',
    childPermissionId: 'view_schedules',
  },

  // Task management implications
  { parentPermissionId: 'create_tasks', childPermissionId: 'view_tasks' },
  { parentPermissionId: 'update_tasks', childPermissionId: 'view_tasks' },
  { parentPermissionId: 'delete_tasks', childPermissionId: 'view_tasks' },
  { parentPermissionId: 'view_all_tasks', childPermissionId: 'view_tasks' },
  {
    parentPermissionId: 'view_all_tasks',
    childPermissionId: 'view_active_tasks',
  },
  {
    parentPermissionId: 'view_all_tasks',
    childPermissionId: 'view_pending_tasks',
  },
  {
    parentPermissionId: 'view_all_tasks',
    childPermissionId: 'view_historical_tasks',
  },
  {
    parentPermissionId: 'view_all_tasks',
    childPermissionId: 'view_overdue_tasks',
  },
  { parentPermissionId: 'assign_task', childPermissionId: 'view_tasks' },

  // Care plan implications
  {
    parentPermissionId: 'create_care_plans',
    childPermissionId: 'view_care_plans',
  },
  {
    parentPermissionId: 'update_care_plans',
    childPermissionId: 'view_care_plans',
  },
  {
    parentPermissionId: 'delete_care_plans',
    childPermissionId: 'view_care_plans',
  },
  {
    parentPermissionId: 'create_care_notes',
    childPermissionId: 'view_care_notes',
  },
  {
    parentPermissionId: 'update_care_notes',
    childPermissionId: 'view_care_notes',
  },
  {
    parentPermissionId: 'delete_care_notes',
    childPermissionId: 'view_care_notes',
  },

  // Medical information implications
  {
    parentPermissionId: 'create_medications',
    childPermissionId: 'view_medications',
  },
  {
    parentPermissionId: 'update_medications',
    childPermissionId: 'view_medications',
  },
  {
    parentPermissionId: 'delete_medications',
    childPermissionId: 'view_medications',
  },
  {
    parentPermissionId: 'create_medical_records',
    childPermissionId: 'view_medical_records',
  },
  {
    parentPermissionId: 'update_medical_records',
    childPermissionId: 'view_medical_records',
  },
  {
    parentPermissionId: 'delete_medical_records',
    childPermissionId: 'view_medical_records',
  },

  // Resident data implications
  {
    parentPermissionId: 'create_resident_data',
    childPermissionId: 'view_residents',
  },
  {
    parentPermissionId: 'update_resident_data',
    childPermissionId: 'view_residents',
  },
  {
    parentPermissionId: 'delete_resident_data',
    childPermissionId: 'view_residents',
  },

  // Shift management implications
  { parentPermissionId: 'create_shift', childPermissionId: 'view_shift' },
  { parentPermissionId: 'update_shift', childPermissionId: 'view_shift' },
  { parentPermissionId: 'delete_shift', childPermissionId: 'view_shift' },
  { parentPermissionId: 'assign_users', childPermissionId: 'view_shift' },

  // Report implications
  { parentPermissionId: 'create_reports', childPermissionId: 'view_reports' },
  { parentPermissionId: 'edit_reports', childPermissionId: 'view_reports' },
  { parentPermissionId: 'delete_reports', childPermissionId: 'view_reports' },

  // Group management implications
  { parentPermissionId: 'edit_group', childPermissionId: 'view_group' },
  { parentPermissionId: 'add_group_member', childPermissionId: 'view_group' },
  { parentPermissionId: 'update_group', childPermissionId: 'view_group' },
  { parentPermissionId: 'delete_group', childPermissionId: 'view_group' },

  // Leave management implications
  {
    parentPermissionId: 'manage_leave_requests',
    childPermissionId: 'view_leave_requests',
  },
  {
    parentPermissionId: 'view_all_leave_balances',
    childPermissionId: 'view_leave_balance',
  },
  {
    parentPermissionId: 'manage_leave_policy',
    childPermissionId: 'view_leave_policy',
  },
];
