import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { apiHostname } from '../config/api';

const shiftTags = [
  'ShiftPatterns',
  'ShiftPattern',
  'OtherShiftPatterns',
  'Shifts',
  'Shift',
  'ShiftsByDate',
  'HomeShifts',
  'AgencyShifts',
  'ShiftAssignments',
  'ShiftAssignment',
  'UserAssignments',
];

// Create a wrapper for the base query
const baseQueryWithAuth = fetchBaseQuery({
  baseUrl: `${apiHostname}/api/v1`,
  prepareHeaders: async (headers, { getState }) => {
    const token = await localStorage.getItem('token');
    if (token) {
      headers.set('Authorization', `Bearer ${token}`);
    }
    headers.set('Accept', 'application/json');
    headers.set('Content-Type', 'application/json');
    return headers;
  },
});

// Create an error handling wrapper
const baseQueryWithErrorHandler = async (
  args: any,
  api: any,
  extraOptions: any
) => {
  const result: any = await baseQueryWithAuth(args, api, extraOptions);

  if (result?.error) {
    console.error('Error:', result);
  }

  return result;
};

export const baseApi = createApi({
  reducerPath: 'api',
  baseQuery: baseQueryWithErrorHandler,
  tagTypes: [
    ...shiftTags,
    'OtherShiftPatterns',
    'ShiftPatterns',
    'OrganizationStaff',
    'StaffInvitations',
    'Organization',
    'Profile',
    'WoundV2',
    'RecentTasksV2',
    'TestResidents',
    'DefaultFormConfig',
    'ResidentAnalytics',
    'TaskResolutions',
    'ResolutionForm',
    'RoutineType',
    'ResidentAnalytics',
    'ResolutionForms',
    'Tasks',
    'Resolutions',
    'RoutineTypes',
    'SuperAdminStaffsOverview',
    'SuperAdminStaffDevices',
    'SuperAdminUpcomingShifts',
    'ShiftPresets',
    'Medications',
    'TemporaryHomes',
    'TemporaryHome',
    'TemporaryHomeStats',
    'Organizations',
    'EmployeeAvailability',
    'CurrentUserAvailability',
    'AvailableEmployees',
    'EmployeeMetrics',
    'QuickStats',
    'ResidentsV2',
    'ResidentV2',
    'CareRoutineV2',
    'UpcomingTasksV2',
    'DueTasksV2',
    'OverdueTasksV2',
    'TaskStatisticsV2',
    'ResidentTaskHistoryV2',
    'UserOrganization',
    'UserProfile',
    'SuperNotificationTargets',
    'SuperNotificationHistory',
    'User',
    'LinkedOrganizationsPaginated',
    'ShiftsForTheDay',
    'SHomes',
    'ResidentAnalysis',
    'VitalSigns',
    'Nutrition',
    'Medication',
    'CareHygiene',
    'Sleep',
    'ResidentAlerts',
    'Alerts',
    'SkillsData',
    'LanguagesData',
    'CareSkillsData',
    'SpecializationsData',
    'CarerApplication',
    'AgencyApplication',
    'ApplicationData',
    'ApplicationStatus',
    'ProgressSummary',
    'NotificationSettings',
    'NotificationQuota',
    'Attendance',
    'Organizations',
    'AttendanceScanner',
    'WorkplaceQR',
    'WorkplaceAttendance',
    'UserAttendance',
    'AttendanceStatus',
    'LeaveRequests',
    'LeaveBalance',
    'LeavePolicy',
    //payments
    'TimesheetAdmins',
    'Groups',
    'SubscriptionDetails',
    'AllPlans',
    'Plans',
    'PlanDetails',
    'Shifts',
    'AssignedStaffs',
    'AvailableStaff',
    'AgencyAnalytics',
    'ChatGroups',
    'GroupMessages',
    'GroupUnread',
    'DirectMessages',
    'Conversations',
    'UnreadCount',
    'ShiftType',
    'ShiftPattern',
    'Invoice',
    'Resident',
    'Task',
    'AssignedStaffs',
    'CarePlan',
    'Application',
    'Shift',
    'AgencyShift',
    'Payment',
    'ChatMessages',
    'Notifications',
    'NotificationsCount',
    'StaffsForChat',
    'Staffs',
    'Timesheets',
    'Invitations',
    'Agencies',
    'LinkedOrganizations',
    'LinkedOrgranizationAdmins',
    'LinkedOrganizationAdminForCarer',
    'Analytics',
    'StaffAnalytics', // Staff-related metrics
    'ShiftAnalytics', // Shift-related metrics
    'RevenueAnalytics', // Revenue-related metrics
    'CareHomeAnalytics', // Care home relationship metrics
    'StaffingTrends', // Staffing demand trends
    'UpcomingRequirements', // Upcoming shift requirements
    'DailyMetrics', // Daily performance metrics
    'WeeklyMetrics', // Weekly aggregated metrics
    'MonthlyMetrics', // Monthly aggregated metrics
    'StaffUtilization', // Staff utilization metrics
    'ShiftFillRate', // Shift fill rate metrics
    'RevenueGrowth', // Revenue growth metrics
    'CareHomeEngagement', // Care home engagement metrics
    'UrgentRequirements', // Urgent staffing needs
    'StaffAvailability',
    'Invoices',
    'FavoriteStaffs',
    'FavoriteStatus',
    'TaskSummary',
    'tasks',
    'CarePlans',
    'CarePlansReview',
    'CarePlanHistory',
    'CarePlanSummary',
    'CarePlanReview',
    'MedicationPlan',
    'MedicationReview',
    'MedicationHistory',
    'padCheckAnalysis',
    'PadCheckReview',
    'PadCheckPlan',
    'SkinConditionHistory',
    'PadCheckHistory',
    'PadCheckStats',
    'VitalSignPlan',
    'VitalSignReview',
    'VitalSignHistory',
    'VitalSignStats',
    'VitalSignPlanHistory',
    'NutritionPlan',
    'NutritionReview',
    'NutritionHistory',
    'NutritionPlanHistory',
    'NutritionStats',
    'IntakeStats',
    'IntakeReview',
    'IntakeHistory',
    'IntakePlan',
    'IntakePlanHistory',
    'ComplianceStats',
    'FluidIntakePlan',
    'FluidIntakeReview',
    'FluidIntakePlanHistory',
    'FluidIntakeStats',
    'DailyIntake',
    'FluidIntakeHistory',
    'HygienePlan',
    'HygieneReview',
    'HygieneHistory',
    'HygienePlanHistory',
    'HygieneStats',
    'HygienePlanSummary',
    'PositioningPlan',
    'PositioningReview',
    'PositioningHistory',
    'PositioningStats',
    'PositioningPlanHistory',
    'PositioningTask',
    'BathingPlan',
    'BathingReview',
    'BathingHistory',
    'BathingTask',
    'BathingTaskHistory',
    'SkinAssessment',
    'SkinAssessmentHistory',
    'BathingPreferences',
    'ExercisePlan',
    'ExerciseReview',
    'ExerciseHistory',
    'ExerciseSession',
    'ProgressStats',
    'ExerciseStats',
    'ExercisePlanSummary',
    'ExercisePlanReview',
    'AchievementReport',
    'SocialEngagementPlan',
    'SocialEngagementReview',
    'SocialEngagementHistory',
    'SocialActivity',
    'ParticipationStats',
    'BehavioralPlan',
    'BehavioralReview',
    'BehavioralHistory',
    'BehavioralAssessment',
    'SocializationMetrics',
    'SleepCarePlan',
    'SleepCareReview',
    'SleepHistory',
    'SleepActivity',
    'SleepQualityStats',
    'SleepPlanSummary',
    'SleepPlanReview',
    'SleepPlanHistory',
    'SleepSession',
    'SleepSessionHistory',
    'SleepMetrics',
    'NightTimeBehavioralAssessment',
    'WoundCarePlan',
    'WoundCareReview',
    'WoundHistory',
    'WoundActivity',
    'WoundAssessment',
    'WoundAssessmentHistory',
    'WoundAssessmentReview',
    'WoundAssessmentSummary',
    'WoundAssessmentStats',
    'WoundAssessmentPlan',
    'WoundActivity',
    'HealingStats',
    'HealingStats',
    'InfectionAssessment',
    'WoundMetrics',
    'RecentChats',
    'BroadcastMessages',
    'MessageReplies',
  ],
  endpoints: () => ({}),
});

// Export types if needed
export type BaseApiType = typeof baseApi;
